name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Test
        run: dotnet build api-producer/api-producer.slnx
        
      - name: Test worker
        run: dotnet build worker-consumer/worker-consumer.slnx
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build frontend
        run: cd angular-client && npm install && npm run build
