name: Enterprise Platform CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore Backend Dependencies
      run: |
        dotnet restore src/OrderService/OrderService.slnx
        dotnet restore src/InventoryService/InventoryService.slnx
        dotnet restore src/ApiGateway/src/ApiGateway/ApiGateway.csproj

    - name: Build Backend
      run: |
        dotnet build --no-restore src/OrderService/OrderService.slnx
        dotnet build --no-restore src/InventoryService/InventoryService.slnx
        dotnet build --no-restore src/ApiGateway/src/ApiGateway/ApiGateway.csproj

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: Install Frontend Dependencies
      run: npm install
      working-directory: ./src/WebFrontend/AngularApp

    - name: Build Angular App
      run: npm run build
      working-directory: ./src/WebFrontend/AngularApp
